- build.gradle
- src/main/java/com/hp/triclops/SimpleConfig.java
- src/main/java/com/hp/triclops/entity/User.java
- src/main/java/com/hp/triclops/redis/SessionRedis.java
- src/main/java/com/hp/triclops/repository/UserRepository.java
- src/test/java/com/hp/triclops/RedisTest.java
https://github.com/HP-Enterprise/BriAir/issues/19
> SessionRedis

- src/main/java/com/hp/triclops/SimpleConfig.java
- src/main/java/com/hp/triclops/redis/SessionRedis.java
- src/test/java/com/hp/triclops/RedisTest.java
- src/test/resources/application-sample.properties
> 新增redis存储KEY的前缀

- src/main/java/com/hp/triclops/redis/SessionRedis.java
- src/test/java/com/hp/triclops/RedisTest.java
> 修改了对KEY值是否存在的判断逻辑。

- src/main/java/com/hp/triclops/redis/Verifier.java
- src/test/java/com/hp/triclops/VerifierTest.java
> 完成Verifier类生成与校验验证码功能

- .gitignore
- README.md
- build.gradle
- gradle-sample.properties
- src/main/resources/db/migration/V20150804.1__user.sql
- src/main/resources/db/migration/V20150817.1__t_account.sql
https://github.com/HP-Enterprise/BriAir/issues/41#event-390058729
@AceBear 
使用命令行工具spring-boot + flyway自动化执行数据库脚本
> 使用命令行工具spring-boot + flyway自动化执行数据库脚本

- src/main/java/com/hp/triclops/redis/Verifier.java
- src/test/java/com/hp/triclops/VerifierTest.java
> 增加判断校验码时间是否过期判断

- src/main/java/com/hp/triclops/redis/SessionRedis.java
- src/test/java/com/hp/triclops/RedisTest.java
> 增加了查询全部session值方法

- src/main/java/com/hp/triclops/repository/VehicleRepositiryDAO.java
> 完善车辆查询，支持模糊、精确查询

- src/main/java/com/hp/triclops/redis/SessionRedis.java
> 补充SessionRedis类注释信息

- src/main/java/com/hp/triclops/entity/Vehicle.java
- src/main/java/com/hp/triclops/repository/VehicleRepositiryDAO.java
- src/main/resources/db/migration/V20150820.1__vehicle.sql
> vehicle数据表增加id字段

- src/main/java/com/hp/triclops/entity/Vehicle.java
- src/main/java/com/hp/triclops/repository/VehicleRepository.java
> 车辆管理API bug修改

- src/main/java/com/hp/triclops/acquire/AcquirePort.java
#182
https://github.com/HP-Enterprise/BriAir/issues/182
回声服务器用浏览器访问会导致进程退出 已解决
> 修改遍历方法，消除导致进程退出的问题

- src/main/java/com/hp/triclops/entity/SlotInfo.java
- src/main/java/com/hp/triclops/repository/SlotRepository.java
- src/main/resources/db/migration/V20150910.1__t_slot.sql
> 修改通讯录实体uid为int类型

- src/main/java/com/hp/triclops/repository/UserRepositiryDAO.java
- src/main/java/com/hp/triclops/repository/VehicleRepositiryDAO.java
- src/main/java/com/hp/triclops/utils/EscapeStringUtil.java
https://github.com/HP-Enterprise/BriAir/issues/239
> 处理转义字符查询问题，改了用户查询和车辆查询相关的部分

- src/main/java/com/hp/triclops/entity/Organization.java
- src/main/java/com/hp/triclops/entity/UserVehicleRelatived.java
- src/main/java/com/hp/triclops/entity/Vehicle.java
- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepository.java
- src/main/java/com/hp/triclops/repository/VehicleRepository.java
- src/main/resources/db/migration/V20150820.1__vehicle.sql
- src/main/resources/db/migration/V20150906.1__t_user_vehicle_relatived.sql
- src/main/resources/db/migration/V20150907.1__organization_vehicle.sql
- src/test/java/com/hp/triclops/DemoTest.java
- src/test/java/com/hp/triclops/OrganizationTest.java
- src/test/java/com/hp/triclops/VerifierTest.java
> 修改用户绑定车辆和解绑API

- src/main/java/com/hp/triclops/repository/VehicleRepositoryDAO.java
> vehicle支持oid查询参数

- src/main/java/com/hp/triclops/repository/SysdictRepository.java
- src/main/resources/db/migration/V20150917.1__t_slot.sql
> 创建组织加入缺省父组织和缺省权限组

- src/main/java/com/hp/triclops/entity/OrganisationVehicleRelatived.java
- src/main/java/com/hp/triclops/repository/OrganisationVehicleRelativedRepository.java
- src/main/java/com/hp/triclops/repository/VehicleRepository.java
- src/main/java/com/hp/triclops/repository/VehicleRepositoryDAO.java
- src/main/resources/db/migration/V20150901.2__t_organization.sql
https://github.com/HP-Enterprise/BriAir/issues/352
> 添加组织与车辆关系API

- src/main/java/com/hp/triclops/Application.java
- src/main/java/com/hp/triclops/acquire/AcquirePort.java
- src/main/java/com/hp/triclops/acquire/DataTool.java
- src/main/java/com/hp/triclops/acquire/Receiver.java
- src/main/java/com/hp/triclops/acquire/Sender.java
- src/main/java/com/hp/triclops/acquire/Server.java
- src/main/java/com/hp/triclops/redis/SocketRedis.java
https://github.com/HP-Enterprise/BriAir/issues/296
https://github.com/HP-Enterprise/BriAir/issues/297
已完成issuse功能要求
> Dev data receive send

- src/main/java/com/hp/triclops/repository/UserRepositoryDAO.java
> 改为采用PersistenceContext自带的分页方法

- src/main/java/com/hp/triclops/repository/OrganizationRepository.java
> 根据组织简码查询组织

- src/main/java/com/hp/triclops/entity/User.java
- src/main/java/com/hp/triclops/repository/UserRepositoryDAO.java
https://github.com/HP-Enterprise/BriAir/issues/445
> 增加vin查询与建立User表和Vehicle表关系

- src/main/resources/db/migration/V20150930.1__pro_findusers.sql
> 解决存储过程sql脚本的warning

- src/main/java/com/hp/triclops/acquire/RequestHandler.java
> javadoc 注释修改

- src/main/java/com/hp/triclops/entity/Org6S.java
- src/main/java/com/hp/triclops/entity/Vehicle6S.java
> 修改方法名以及加上javaDoc注释

- src/main/java/com/hp/triclops/acquire/NettyServerHandler.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/test/java/com/hp/triclops/OutputHexServiceTest.java
https://github.com/HP-Enterprise/BriAir/issues/598 完成
> Dev push warning message

- src/main/java/com/hp/triclops/repository/VehicleRepository.java
- src/main/java/com/hp/triclops/repository/VehicleRepositoryDAO.java
- src/main/resources/db/migration/V20151012.1__pro_findvehicles.sql
> 根据tboxsn查询车辆

- src/main/java/com/hp/triclops/acquire/RequestHandler.java
> Dev register bug

- src/main/java/com/hp/triclops/manager/Org6S.java
- src/main/java/com/hp/triclops/manager/Vehicle6S.java
- src/main/java/com/hp/triclops/repository/UserRepositoryDAO.java
- src/main/java/com/hp/triclops/repository/VehicleRepositoryDAO.java
> 消除javaDoc警告

- src/main/java/com/hp/triclops/acquire/DataHandler.java
- src/main/java/com/hp/triclops/acquire/DataHandlerThread.java
- src/main/java/com/hp/triclops/acquire/NettyServer.java
> Dev data server improve2

- src/main/java/com/hp/triclops/repository/SysdictRepositoryDAO.java
> 完成编写查询字典API

- src/main/java/com/hp/triclops/acquire/NettyServerHandler.java
https://github.com/HP-Enterprise/BriAir/issues/798
电检、激活流程优先于注册  完成
> 电检、激活流程优先于注册  完成

- src/main/java/com/hp/triclops/manager/TBoxMgr.java
- src/main/java/com/hp/triclops/repository/TBoxRepositoryDAO.java
- src/test/java/com/hp/triclops/TboxTest.java
> Fixed get/api/tbox

- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/test/java/com/hp/triclops/DataToolTest.java
> 修正参数设置和远程诊断命令重发bug

- src/main/java/com/hp/triclops/user/PwdEvidence.java
- src/main/java/com/hp/triclops/user/PwdLogin.java
- src/main/java/com/hp/triclops/user/PwdLoginInfo.java
- src/main/java/com/hp/triclops/user/PwdRegist.java
- src/main/java/com/hp/triclops/user/User.java
- src/main/java/com/hp/triclops/user/UserAndPwd.java
- src/main/java/com/hp/triclops/user/UserManagement.java
[#888](https://github.com/HP-Enterprise/BriAir/issues/888)
> 用户登录相关类迁移设计

- src/main/java/com/hp/triclops/manager/TBoxMgr.java
- src/main/java/com/hp/triclops/repository/TBoxRepositoryDAO.java
解决警告信息
HP-Enterprise/BriAir#879
> 解决TBOX check 警告

- src/main/java/com/hp/triclops/manager/TBoxMgr.java
- src/main/java/com/hp/triclops/repository/TBoxRepositoryDAO.java
- src/main/java/com/hp/triclops/utils/Page2.java
原因Page2 set方法有问题，此pr可以完全覆盖上次pr  #879
> 解决查询tbox空指针

- src/main/java/com/hp/triclops/repository/UserRepository.java
- src/main/java/com/hp/triclops/user/UserManagement.java
- src/main/java/com/hp/triclops/user/vo/UserShow.java
[#949](https://github.com/HP-Enterprise/BriAir/issues/949)
> 完成Triclops中UserManagement类

- src/main/java/com/hp/triclops/repository/UserRepositoryDAO.java
- src/main/resources/db/migration/V20150930.1__pro_findusers.sql
- src/main/resources/db/migration/V20151012.1__pro_findvehicles.sql
https://github.com/HP-Enterprise/BriAir/issues/937
> 解决多个组织管理员，不能查询所有组织下车辆及用户BUG,已测试 

- src/main/java/com/hp/triclops/user/vo/UserShow.java
[#1055](https://github.com/HP-Enterprise/BriAir/issues/1055)
> 修改用户VO类构造方法

- src/main/resources/db/migration/V20150804.1__t_user.sql
> 管理添加一个默认的性别

- src/main/java/com/hp/triclops/user/UserManagement.java
- src/main/java/com/hp/triclops/vo/UserShow.java
https://github.com/HP-Enterprise/BriAir/issues/1086
> UserShow类迁移

- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepository.java
- src/main/java/com/hp/triclops/vehicle/VehicleManagement.java
> 完成Triclops/vehicle/VehicleManagement 中的两个成员方法

- src/main/java/com/hp/triclops/vo/PhoneBookShow.java
[#1095](https://github.com/HP-Enterprise/BriAir/issues/1095)
> 补全PhoneBookShow类

- src/main/java/com/hp/triclops/entity/User.java
- src/main/resources/db/migration/V20150804.1__t_user.sql
https://github.com/HP-Enterprise/BriAir/issues/1080
> 增加user 图标字段，增加sql脚本

- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepository.java
- src/main/java/com/hp/triclops/vehicle/VehicleManagement.java
> 修正方法VehicleManagement::updateUserVehicleRelatived

- src/main/java/com/hp/triclops/phoneBook/PhoneBookManagement.java
- src/main/java/com/hp/triclops/repository/PhoneBookRepositoryDAO.java
https://github.com/HP-Enterprise/BriAir/issues/1097
> 完成com.hp.triclops.phoneBook.PhoneBookManagement类

- src/main/java/com/hp/triclops/vehicle/VehicleManagement.java
- src/main/java/com/hp/triclops/vo/VehicleShow.java
https://github.com/HP-Enterprise/BriAir/issues/1128
> 修改车辆管理类查询默认车辆方法

- src/main/java/com/hp/triclops/repository/PhoneBookRepositoryDAO.java
https://github.com/HP-Enterprise/BriAir/issues/1099
> 修改PhoneBookRepositoryDAO::get方法

- src/main/java/com/hp/triclops/phoneBook/PhoneBookManagement.java
- src/main/java/com/hp/triclops/repository/PhoneBookRepository.java
- src/main/java/com/hp/triclops/repository/PhoneBookRepositoryDAO.java
https://github.com/HP-Enterprise/BriAir/issues/1192
> 修改删除联系人API

- src/main/java/com/hp/triclops/repository/PhoneBookRepository.java
- src/main/java/com/hp/triclops/repository/PhoneBookRepositoryDAO.java
https://github.com/HP-Enterprise/BriAir/issues/1203
> 完成通讯录管理API

- src/main/java/com/hp/triclops/entity/Vehicle.java
- src/main/java/com/hp/triclops/vo/VehicleShow.java
[#1233](https://github.com/HP-Enterprise/BriAir/issues/1233)
> 完善vehicle,vehicleShow中的注释

- src/main/java/com/hp/triclops/entity/Shop4s.java
- src/main/java/com/hp/triclops/repository/FSShopReposittory.java
- src/main/resources/db/migration/V20151118.2__t_fs_shop.sql
> 保养管理-根据城市查询4S店，返回电话，地址，城市

- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/main/java/com/hp/triclops/utils/HttpRequestTool.java
- src/main/java/com/hp/triclops/utils/HttpRequestor.java
- src/main/resources/application.yml
- src/test/java/com/hp/triclops/HttpRequestorTest.java
- src/test/resources/application.yml
> 车辆数据采集推送修改

- src/main/java/com/hp/triclops/entity/RealTimeReportData.java
- src/main/java/com/hp/triclops/service/DataHandleService.java
- src/main/resources/db/migration/V20151008.1__t_data_realtime_report.sql
> add column trip_id

- src/main/java/com/hp/triclops/acquire/CommandHandler.java
- src/main/java/com/hp/triclops/acquire/DataTool.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/main/java/com/hp/triclops/service/VehicleDataService.java
修改参数设置下发时间及eventId来源为系统当前时间
修改部分数据存储redis的ttl
> 修改参数设置下发时间及eventId来源为系统当前时间

- src/main/java/com/hp/triclops/vo/UserShow.java
https://github.com/HP-Enterprise/BriAir/issues/1377
> 修改User实体类对应vo

- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/test/java/com/hp/triclops/VehicleDataServiceTest.java
> 参数设置命令车牌部分修改

- src/main/java/com/hp/triclops/vo/UserVehicleRelativedShow.java
https://github.com/HP-Enterprise/BriAir/issues/1400
> 保存自定义保养提醒鉴权

- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepositoryDAO.java
https://github.com/HP-Enterprise/BriAir/issues/1401
> 升级查询车主车辆关系API

- src/main/java/com/hp/triclops/entity/DiagnosticData.java
- src/main/java/com/hp/triclops/repository/DiagnosticDataRepository.java
- src/main/java/com/hp/triclops/repository/DiagnosticDataRepositoryDao.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
https://github.com/HP-Enterprise/BriAir/issues/1392#event-477262696
> 车辆诊断数据缓存问题

- src/main/java/com/hp/triclops/manager/TBoxMgr.java
HP-Enterprise/BriAir/pull/1420
> 解决修改tbox时，会解除与车辆的绑定

- src/main/java/com/hp/triclops/service/VehicleDataService.java
- src/main/java/com/hp/triclops/vo/RealTimeDataShow.java
https://github.com/HP-Enterprise/BriAir/issues/1424
> 修改目前程序接口与接口文档不一致的地方

- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepositoryDAO.java
https://github.com/HP-Enterprise/BriAir/issues/1430
> 修改车辆用户关系库方法

- src/main/resources/db/migration/V20150930.1__pro_findusers.sql
- src/main/resources/db/migration/V20151012.1__pro_findvehicles.sql
#937 避免 用户表及车辆表新增和删除字段  引起的字段不匹配
> 修改 查询用户及车辆的存储过程

- src/main/java/com/hp/triclops/entity/PhoneBook.java
- src/main/resources/db/migration/V20151111.1__t_phone_book.sql
https://github.com/HP-Enterprise/BriAir/issues/1455
> 修改通讯录电话号码11位限制

- src/main/java/com/hp/triclops/acquire/NettyServerHandler.java
- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/test/java/com/hp/triclops/RequestHandlerTest.java
https://github.com/HP-Enterprise/BriAir/issues/1421
> 修改TBOX唤醒流程

- src/main/java/com/hp/triclops/service/OutputHexService.java
...
https://github.com/HP-Enterprise/BriAir/issues/1508
> change true to "1"

- src/main/java/com/hp/triclops/manager/TBoxMgr.java
- src/main/java/com/hp/triclops/repository/TBoxRepositoryDAO.java
- src/test/java/com/hp/triclops/TboxTest.java
HP-Enterprise/BriAir/issues/1546
> 给tbox添加一个查询全部的字段

- src/main/resources/db/migration/V20151022.1__t_sysdict.sql
添加公共群
https://github.com/HP-Enterprise/BriAir/issues/1577
> 修改typeKey的sql表

- src/main/java/com/hp/triclops/service/OutputHexService.java
> 修复远程控制执行结果处理

- src/main/java/com/hp/triclops/entity/Message.java
- src/main/resources/db/migration/V20151009.1__t_message.sql
> 添加Message表字段

- src/main/resources/db/migration/V20150804.1__t_user.sql
> 修改ICON 字段长度

- src/main/java/com/hp/triclops/entity/Message.java
- src/main/resources/db/migration/V20151009.1__t_message.sql
> 修改message表结构

- src/main/java/com/hp/triclops/entity/OrganisationVehicleRelativeEx.java
- src/main/java/com/hp/triclops/entity/VehicleEx.java
- src/main/java/com/hp/triclops/management/OrganizationUserManagement.java
- src/main/java/com/hp/triclops/management/OrganizationVehicleManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/OrganisationVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/OrganizationUserRelativeRepository.java
- src/main/java/com/hp/triclops/repository/VehicleExRepository.java
- src/main/java/com/hp/triclops/vo/OrganisationVehicleRelativeExShow.java
- src/main/java/com/hp/triclops/vo/VehicleExShow.java
https://github.com/HP-Enterprise/BriAir/issues/1939
> 重构组织车辆关系模块

- src/main/java/com/hp/triclops/entity/UserVehicleRelativeEx.java
- src/main/java/com/hp/triclops/management/UserVehicleManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/UserVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepository.java
- src/main/resources/db/migration/V20150906.1__t_user_vehicle_relatived.sql
https://github.com/HP-Enterprise/BriAir/issues/1940
> 重构用户车辆关系模块

- src/main/java/com/hp/triclops/management/OrganizationManagement.java
- src/main/java/com/hp/triclops/management/OrganizationUserManagement.java
- src/main/java/com/hp/triclops/management/OrganizationVehicleManagement.java
- src/main/java/com/hp/triclops/management/UserManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/OrganisationVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/OrganizationUserRelativeRepository.java
- src/main/resources/db/migration/V20150820.1__t_vehicle.sql
https://github.com/HP-Enterprise/BriAir/issues/1968
> 修改组织管理相关API

- src/main/java/com/hp/triclops/entity/OrganisationVehicleRelativeEx.java
- src/main/java/com/hp/triclops/management/OrganizationVehicleManagement.java
- src/main/java/com/hp/triclops/repository/OrganisationVehicleRelativeExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/1988
> 修改从组织删除车辆API

- src/main/java/com/hp/triclops/management/OrganizationUserManagement.java
- src/main/java/com/hp/triclops/management/OrganizationVehicleManagement.java
- src/main/java/com/hp/triclops/repository/OrganisationVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/OrganizationUserRelativeRepository.java
https://github.com/HP-Enterprise/BriAir/issues/1994
> 修改向权限组增加用户API

- src/main/java/com/hp/triclops/entity/OrganizationEx.java
https://github.com/HP-Enterprise/BriAir/issues/2006
> 修改权限组授权API

- src/main/java/com/hp/triclops/management/UserManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/vo/VehicleExShow.java
https://github.com/HP-Enterprise/BriAir/issues/2033
> 修改组织增加车辆查询不到车辆的问题

- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/main/java/com/hp/triclops/utils/HttpRequestTool.java
解决push message cleanFlag标识不正确问题
> 解决push message cleanFlag标识不正确问题

- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/vo/VehicleExShow.java
https://github.com/HP-Enterprise/BriAir/issues/2109
> 修改根据vid查询车辆信息API

- src/main/java/com/hp/triclops/service/VehicleDataService.java
- src/main/java/com/hp/triclops/vo/RealTimeDataShow.java
https://github.com/HP-Enterprise/BriAir/issues/2178
> 平均油耗变为平均油耗 A B

- src/main/java/com/hp/triclops/repository/UserVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2276
> 修改通过车辆ID查询用户与车辆关系方法

- src/main/java/com/hp/triclops/repository/UserVehicleRelativeExRepository.java
> 修改根据用户ID查询用户与车辆关系方法

- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/UserVehicleRelativedRepository.java
- src/main/java/com/hp/triclops/repository/VehicleExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2303
> 增加根据车辆ID集合批量查询车辆信息方法

- src/main/java/com/hp/triclops/management/VehicleManagement.java
https://github.com/HP-Enterprise/BriAir/issues/2317
> 增加安防密码校验方法

- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/VehicleExRepository.java
- src/main/java/com/hp/triclops/repository/VehicleRepository.java
- src/main/java/com/hp/triclops/vo/UserVehicleRelativeExShow.java
https://github.com/HP-Enterprise/BriAir/issues/2325
> 修改用户车辆管理方法

- src/main/java/com/hp/triclops/management/OrganizationVehicleManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/OrganisationVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/VehicleExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2342
> 新增查询组织外车辆方法

- src/main/java/com/hp/triclops/management/OrganizationUserManagement.java
- src/main/java/com/hp/triclops/management/UserManagement.java
- src/main/java/com/hp/triclops/repository/OrganizationUserRelativeRepository.java
- src/main/java/com/hp/triclops/repository/UserExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2345
> 编写查询组织外用户方法

- src/main/java/com/hp/triclops/management/OrganizationUserManagement.java
- src/main/java/com/hp/triclops/repository/OrganizationUserRelativeRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2350
> 增加查询组织权限组外的组织成员方法

- src/main/java/com/hp/triclops/service/VehicleDataService.java
https://github.com/HP-Enterprise/BriAir/issues/2359
> 增加短信唤醒TBOX

- src/main/java/com/hp/triclops/management/OrganizationVehicleManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/OrganisationVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/VehicleExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2363
> 查询组织中的车辆方法调优

- src/main/java/com/hp/triclops/management/UserManagement.java
- src/main/java/com/hp/triclops/repository/UserExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2364
> 修改注册查询用户方法

- src/main/java/com/hp/triclops/management/OrganizationUserManagement.java
- src/main/java/com/hp/triclops/management/UserManagement.java
- src/main/java/com/hp/triclops/repository/OrganizationUserRelativeRepository.java
- src/main/java/com/hp/triclops/repository/UserExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2366
> 修改查询权限组外组织成员方法

- src/main/java/com/hp/triclops/management/UserManagement.java
- src/main/java/com/hp/triclops/repository/UserExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2372
> 新增批量查询用户信息API

- src/main/java/com/hp/triclops/management/OrganizationManagement.java
- src/main/java/com/hp/triclops/repository/OrganizationExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2376
> 新增批量查询组织方法

- src/main/java/com/hp/triclops/entity/TBoxEx.java
- src/main/java/com/hp/triclops/management/TBoxManagement.java
- src/main/java/com/hp/triclops/manager/Org6S.java
- src/main/java/com/hp/triclops/repository/TBoxExRepository.java
- src/main/java/com/hp/triclops/vo/TBoxExShow.java
https://github.com/HP-Enterprise/BriAir/issues/2379
> 重构TBox管理方法相关类

- src/main/java/com/hp/triclops/entity/TBoxEx.java
- src/main/java/com/hp/triclops/management/TBoxManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/TBoxExRepository.java
- src/main/java/com/hp/triclops/vo/TBoxExShow.java
https://github.com/HP-Enterprise/BriAir/issues/2381
> 完成TBOX管理方法

- src/main/java/com/hp/triclops/entity/TBoxEx.java
- src/main/java/com/hp/triclops/management/TBoxManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/manager/TBoxMgr.java
- src/main/java/com/hp/triclops/vo/TBoxExShow.java
- src/test/java/com/hp/triclops/TboxTest.java
https://github.com/HP-Enterprise/BriAir/issues/2382
> 修改删除TBox方法

- src/main/java/com/hp/triclops/management/TBoxManagement.java
- src/main/java/com/hp/triclops/repository/TBoxExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2389
> 修改新增TBox方法

- src/main/java/com/hp/triclops/management/TBoxManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/manager/Vehicle6S.java
- src/main/java/com/hp/triclops/manager/Vehicle7.java
- src/main/java/com/hp/triclops/repository/TBoxExRepository.java
https://github.com/HP-Enterprise/BriAir/issues/2404
> 修改TBox管理方法

- src/main/java/com/hp/triclops/acquire/DataTool.java
- src/main/java/com/hp/triclops/service/DataHandleService.java
- src/main/java/com/hp/triclops/service/VehicleDataService.java
- src/main/java/com/hp/triclops/vo/RealTimeDataShow.java
剩余燃油 返回百分比取整数
平均油耗保留一位小数
修改实时数据时间为服务器时间
> 经纬度 协议变化 保留6位小数

- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/main/java/com/hp/triclops/service/DataHandleService.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
报警推送问题解决
远程控制失败消息细化
https://github.com/HP-Enterprise/BriAir/issues/2449
> Dev remote message

- src/main/java/com/hp/triclops/management/UserManagement.java
- src/main/java/com/hp/triclops/management/VehicleManagement.java
- src/main/java/com/hp/triclops/repository/UserExRepository.java
- src/main/java/com/hp/triclops/repository/UserVehicleRelativeExRepository.java
- src/main/java/com/hp/triclops/repository/VehicleExRepository.java
- src/main/java/com/hp/triclops/vo/UserVehicleRelativeExShow.java
> 增加查询用户与车辆关系方法

- src/main/java/com/hp/triclops/acquire/AESDownDataHandler.java
- src/main/java/com/hp/triclops/acquire/AESUpDataHandler.java
- src/main/java/com/hp/triclops/acquire/AcquirePort.java
- src/main/java/com/hp/triclops/acquire/DataTool.java
- src/main/java/com/hp/triclops/acquire/NettySender.java
- src/main/java/com/hp/triclops/acquire/NettyServer.java
- src/main/java/com/hp/triclops/acquire/NettyServerHandler.java
- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/main/java/com/hp/triclops/acquire/RequestTask.java
- src/main/java/com/hp/triclops/entity/RemoteControlSettingShow.java
- src/main/java/com/hp/triclops/entity/WarningMessageData.java
- src/main/java/com/hp/triclops/redis/SocketRedis.java
- src/main/java/com/hp/triclops/repository/RemoteControlRepository.java
- src/main/java/com/hp/triclops/repository/TBoxRepository.java
- src/main/java/com/hp/triclops/service/DataHandleService.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/main/java/com/hp/triclops/service/TboxService.java
- src/main/java/com/hp/triclops/service/VehicleDataService.java
- src/main/java/com/hp/triclops/utils/AES128Tool.java
- src/main/resources/db/migration/V20151003.2__t_data_warning_message.sql
- src/main/resources/db/migration/V20151008.3__t_tbox.sql
https://github.com/HP-Enterprise/BriAir/issues/2571
> Dev sep21 a

- src/main/java/com/hp/triclops/acquire/AESDownDataHandler.java
- src/main/java/com/hp/triclops/acquire/AESUpDataHandler.java
- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/main/java/com/hp/triclops/utils/AES128Tool.java
- src/main/java/com/hp/triclops/utils/MD5.java
https://github.com/HP-Enterprise/BriAir/issues/2571
更新AES加密代码，完善密钥补全、转换逻辑（imei/vin/sn md5-16）,解密异常处理
> Dev aes128 new

- src/main/java/com/hp/triclops/acquire/AESDownDataHandler.java
- src/main/java/com/hp/triclops/acquire/AESUpDataHandler.java
- src/main/java/com/hp/triclops/acquire/CommandHandler.java
- src/main/java/com/hp/triclops/acquire/DataHandlerTask.java
- src/main/java/com/hp/triclops/acquire/NettyServerHandler.java
- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/main/java/com/hp/triclops/acquire/RequestTask.java
- src/main/java/com/hp/triclops/service/DataHandleService.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/main/java/com/hp/triclops/service/VehicleDataService.java
https://github.com/HP-Enterprise/BriAir/issues/2586
> 日志中文化，加tag便于日志分析程序处理

- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/main/java/com/hp/triclops/service/VehicleDataService.java
https://github.com/HP-Enterprise/BriAir/issues/2649
https://github.com/HP-Enterprise/BriAir/issues/2650
https://github.com/HP-Enterprise/BriAir/issues/2651
https://github.com/HP-Enterprise/BriAir/issues/2652
> issue 2649 2650 2651 2652

- src/main/java/com/hp/triclops/service/OutputHexService.java
- src/main/java/com/hp/triclops/service/VehicleDataService.java
> 第三次提醒 (提示为小于3次)

- src/main/java/com/hp/triclops/acquire/RequestHandler.java
- src/main/java/com/hp/triclops/service/VehicleDataService.java
> 车速、远程上锁、远程解锁、远程寻车判断条件修改
